In [1]:
import pandas as pd 
import numpy as np
from sklearn.svm import SVC #Support vecter machine
from sklearn.ensemble import RandomForestClassifier #Random Forest
from sklearn.linear_model import LogisticRegression #Logistic Regression
from sklearn.tree import DecisionTreeClassifier #Desicion Trees
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()

In [3]:
from sklearn.model_selection import cross_val_score

In [4]:
svc_scores = cross_val_score(SVC(), iris.data, iris.target, cv = 3) #Resampling data thành 3 tập khác nhau và đưa ra điểm dựa trên 3 tập test thu được

In [5]:
svc_scores

array([0.96, 0.98, 0.94])

In [6]:
np.average(svc_scores) #Lấy điểm trung bình của 3 điểm trên để đưa ra kết quả đánh giá 

0.96

In [7]:
rf_scores = cross_val_score(RandomForestClassifier(), iris.data, iris.target, cv = 3)

In [8]:
rf_scores

array([0.98, 0.94, 0.96])

In [9]:
np.average(rf_scores)

0.96

In [10]:
lr_scoreses = cross_val_score(LogisticRegression(), iris.data, iris.target, cv = 3)

C:\Users\ADMIN\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [11]:
lr_scores

array([0.98, 0.96, 0.98])

In [12]:
np.average(lr_scores)

0.9733333333333333

In [16]:
dt_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target, cv=3)

In [17]:
dt_scores

array([0.98, 0.94, 0.98])

In [18]:
np.average(dt_scores)

0.9666666666666667