In [4]:
from sklearn import svm, datasets

import pandas as pd

In [3]:
iris = datasets.load_iris()

In [5]:
df = pd.DataFrame(iris.data, columns = iris.feature_names)

In [7]:
df['flower'] = iris.target

In [11]:
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])

In [12]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

        flower  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [17]:
from sklearn.model_selection import train_test_split, cross_val_score

In [16]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3)

In [24]:
model = svm.SVC()
model.fit(X_train, y_train)

SVC()

In [25]:
model.score(X_test, y_test)

1.0

In [27]:
cross_val_score(svm.SVC(kernel = 'linear', C=10, gamma='auto'), iris.data, iris.target, cv = 5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [28]:
cross_val_score(svm.SVC(kernel = 'rbf', C=10, gamma='auto'), iris.data, iris.target, cv = 5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [29]:
cross_val_score(svm.SVC(kernel = 'rbf', C=20, gamma='auto'), iris.data, iris.target, cv = 5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [31]:
import numpy as np 
kernels = ['rbf', 'linear']
C = [1, 10, 20]
avg_scores = {}
for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(svm.SVC(kernel = kval, C=cval, gamma='auto'), iris.data, iris.target)
        avg_scores[kval + '_' + str(cval)] = np.average(cv_scores)

avg_scores

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666}

Tiếp cận theo phương pháp K Fold tính điểm trung bình dựa trên cross val nhưng giả sử như ta có hơn 100 model và hàng ngàn hyperparameter thì đây không phải là một cách tiếp cận hợp lý

In [34]:
##GridSearchCV
from sklearn.model_selection import GridSearchCV

clf = GridSearchCV(svm.SVC(gamma = 'auto'), {
    'C': [1,10,20],
    'kernel': ['rbf', 'linear']
}, cv=5, return_train_score=False)

clf.fit(iris.data, iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00100093, 0.00131392, 0.00059409, 0.00068784, 0.00061078,
        0.00090022]),
 'std_fit_time': array([7.46429135e-06, 4.15319635e-04, 4.85139018e-04, 5.83096220e-04,
        4.98861406e-04, 4.91398619e-04]),
 'mean_score_time': array([0.00039787, 0.00080342, 0.00039754, 0.00039902, 0.00080605,
        0.00039148]),
 'std_score_time': array([0.00048735, 0.00040179, 0.00048689, 0.00048869, 0.00068183,
        0.0004796 ]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20

In [37]:
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.001001      0.000007         0.000398        0.000487       1   
1       0.001314      0.000415         0.000803        0.000402       1   
2       0.000594      0.000485         0.000398        0.000487      10   
3       0.000688      0.000583         0.000399        0.000489      10   
4       0.000611      0.000499         0.000806        0.000682      20   
5       0.000900      0.000491         0.000391        0.000480      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

Như chúng ta có thể thấy thì GridSearchCV thực hiện đúng như những gì mà cross_val tính toán nhưng nó tiện lợi hơi và cũng nhanh hơn khi phải lựa chọn mô hình phù hợp trong số nhiều các mô hình khác

In [39]:
from sklearn.model_selection import RandomizedSearchCV

In [47]:
rs = RandomizedSearchCV(svm.SVC(gamma='auto'), {
    'C': [1,10,20],
    'kernel': ['rbf', 'linear']
}, cv=5, return_train_score=False, n_iter=2)

rs.fit(iris.data, iris.target)
pd.DataFrame(rs.cv_results_)

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_kernel  \
0       0.000867      0.000453         0.000997        0.000001       linear   
1       0.001001      0.000007         0.003052        0.000623          rbf   

  param_C                        params  split0_test_score  split1_test_score  \
0       1  {'kernel': 'linear', 'C': 1}           0.966667                1.0   
1      20    {'kernel': 'rbf', 'C': 20}           0.966667                1.0   

   split2_test_score  split3_test_score  split4_test_score  mean_test_score  \
0           0.966667           0.966667                1.0         0.980000   
1           0.900000           0.966667                1.0         0.966667   

   std_test_score  rank_test_score  
0        0.016330                1  
1        0.036515                2

RandomSearchCV thì sẽ lựa chọn ngẫu nhiên parameter cho mô hình mỗi lần Excute thì sẽ trả về một tham số ngẫu nhiên khác nhau

In [50]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [51]:
model_params = {
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'params': {
            'C': [1,10,20],
            'kernel': ['rbf', 'linear']
        }
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params': {
            'n_estimators': [1, 5, 10]
        }
    },
    'logistic_regression': {
        'model': LogisticRegression(),
        'params': {
            'C': [1,5,10]
        }
    }
}

In [52]:
model_params

{'svm': {'model': SVC(gamma='auto'),
  'params': {'C': [1, 10, 20], 'kernel': ['rbf', 'linear']}},
 'random_forest': {'model': RandomForestClassifier(),
  'params': {'n_estimators': [1, 5, 10]}},
 'logistic_regression': {'model': LogisticRegression(),
  'params': {'C': [1, 5, 10]}}}

In [55]:
scores = []

for model_name, mp in model_params.items():
    clf = GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(iris.data, iris.target)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })

C:\Users\ADMIN\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\ADMIN\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [57]:
pd.DataFrame(scores)

model  best_score                best_params
0                  svm        0.98  {'C': 1, 'kernel': 'rbf'}
1        random_forest        0.96       {'n_estimators': 10}
2  logistic_regression        0.98                  {'C': 10}