In [6]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [7]:
df = pd.read_csv("homeprices.csv")

In [8]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [9]:
df.bedrooms.median()

3.5

In [11]:
import math
median_bedrooms = math.floor(df.bedrooms.median())

In [12]:
median_bedrooms

3

In [19]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)

In [20]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [21]:
reg = linear_model.LinearRegression()

In [24]:
reg.fit(df[['area', 'bedrooms', 'age']], df.price)

LinearRegression()

In [25]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [26]:
reg.intercept_

383724.9999999998

In [30]:
reg.predict([[3000, 3, 40]]) #dự đôán giá nhà với yêu cầu: 3000area, 3 bedrooms, 40 years

C:\Users\ADMIN\anaconda3\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [31]:
#y = m1*x1 + m2*x2 + m3*x3 + b
137.25*3000 + -26025*3 + -6825*40 + 383724.9999999998

444399.9999999998

In [32]:
reg.predict([[2500, 4, 5]]) 

C:\Users\ADMIN\anaconda3\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([588625.])